export const districts = [
  { DISTRICT_ID: 1, DISTRICT_NAME: "เมืองบุรีรัมย์" },
  { DISTRICT_ID: 2, DISTRICT_NAME: "คูเมือง" },
  { DISTRICT_ID: 3, DISTRICT_NAME: "กระสัง" },
  { DISTRICT_ID: 4, DISTRICT_NAME: "นางรอง" },
  { DISTRICT_ID: 5, DISTRICT_NAME: "หนองกี่" },
  { DISTRICT_ID: 6, DISTRICT_NAME: "ละหานทราย" },
  { DISTRICT_ID: 7, DISTRICT_NAME: "ประโคนชัย" },
  { DISTRICT_ID: 8, DISTRICT_NAME: "บ้านกรวด" },
  { DISTRICT_ID: 9, DISTRICT_NAME: "พุทไธสง" },
  { DISTRICT_ID: 10, DISTRICT_NAME: "ลำปลายมาศ" },
  { DISTRICT_ID: 11, DISTRICT_NAME: "สตึก" },
  { DISTRICT_ID: 12, DISTRICT_NAME: "ปะคำ" },
  { DISTRICT_ID: 13, DISTRICT_NAME: "นาโพธิ์" },
  { DISTRICT_ID: 14, DISTRICT_NAME: "หนองหงส์" },
  { DISTRICT_ID: 15, DISTRICT_NAME: "พลับพลาชัย" },
  { DISTRICT_ID: 16, DISTRICT_NAME: "ห้วยราช" },
  { DISTRICT_ID: 17, DISTRICT_NAME: "โนนสุวรรณ" },
  { DISTRICT_ID: 18, DISTRICT_NAME: "ชำนิ" },
  { DISTRICT_ID: 19, DISTRICT_NAME: "บ้านใหม่ไชยพจน์" },
  { DISTRICT_ID: 20, DISTRICT_NAME: "โนนดินแดง" },
  { DISTRICT_ID: 21, DISTRICT_NAME: "บ้านด่าน" },
  { DISTRICT_ID: 22, DISTRICT_NAME: "แคนดง" },
  { DISTRICT_ID: 23, DISTRICT_NAME: "เฉลิมพระเกียรติ" }
];